[registries.cloudsmith]
index = "sparse+https://${{ kit.args.cargo-host }}${{ kit.args.path }}/"
credential-provider = "cargo:token"

[source.crates-io]
replace-with = "cloudsmith"

[source.cloudsmith]
registry = "sparse+https://${{ kit.args.cargo-host }}${{ kit.args.path }}/"

[registry]
global-credential-providers = ["cargo:token"]
